### ISSUE TITLE
Can't start without .hz folder

### ISSUE THREAD

**Issue by oskarer** [shanecav/horizon-redux-saga#1]
Trying to start the Horizon server with `hz serve --dev` I get the error "this directory doesn't contain an .hz directory". Looks like .hz is in .gitignore, which it should (?), but how do I start it if it isn't present?

**Comment by shanecav** [comment]
Hi @oskarer, you have to run `hz init` in the horizon-redux-saga folder before running `hz serve --dev`. I forgot to include that step in the instructions, sorry about that! I just updated the README to account for that step.

(I also just bumped the `@horizon/client` package version to 2.0.0, so you'll want to re-clone and then run `npm install` again if you're using Horizon 2.0).

Let me know if you run into any more issues!

**Comment by oskarer** [comment]
Thanks, was able to start the Horizon server when doing that. However it seems like dist/index.html is missing and doing `hz init` does not create that if doing it in an existing folder.

**Comment by shanecav** [comment]
Are you running the app via `npm start`? If so, there isn't a need for an actual dist/index.html file, since webpack is compiling and serving assets from memory. You can just run `npm start` and then visit http://localhost:3000 to use the example app.

**Comment by oskarer** [comment]
I found the error, was running two webpack servers at the same time; both on port 3000. Killing the other one fixed it. Thanks for your help and great job with this repo :)

**Comment by shanecav** [comment]
No problem, glad you got it figured out. And Thanks! :)

**Comment by yedu12** [comment]
Try running the command in the /<Application-name> directory
